[images]
  remote_images = [
    "https://ext.same-assets.com/*"
  ]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://yourserved-clone.netlify.app"
  NODE_VERSION = "20"
  NETLIFY_NEXT_RUNTIME = "nodejs"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"
  NETLIFY_USE_BUN = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
