[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://yourserved-clone.netlify.app"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[images]
  remote_images = [
    "https://ext.same-assets.com/*"
  ]
