[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_PUBLIC_BASE_URL = "/"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
