# Cloudflare Pages configuration
name = "yourserved-clone"
compatibility_date = "2023-12-01"

[build]
command = "npm run build"
upload.format = "directory"

[site]
bucket = "./dist"

# This is the key property Cloudflare Pages looks for
pages_build_output_dir = "dist"

[build.environment]
NODE_VERSION = "16"
